files:
  - source: /**/*.*
    ignore:
      - /**/%two_letters_code%*.*
    translation: /**/%two_letters_code%_%original_file_name%
    languages_mapping:
      two_letters_code:
        nl-BE: cs
      three_letters_code:
        zh-TW: css
