
"project_identifier" : "nml-test"
"api_key" : "0b79e005b97b3a4e2cb76f90c1efc864"
"preserve_hierarchy": true

files: [
 {
  "source" : "/en.po",
  "translation" : "/%two_letters_code%.po"
 },
 {
  "source" : "/**/locale/en/LC_MESSAGES/*.po",
  "translation" : "/**/locale/%two_letters_code%/LC_MESSAGES/%original_file_name%"
 }
]






#files:
#  - source: /**/*.*
#    ignore:
#      - /**/*%two_letters_code%*.*
#    translation: /**/%two_letters_code%_%original_file_name%
#    languages_mapping:
#      two_letters_code:
#        zh-TW: cs
#        nl-BE: th
